#!/bin/bash

version=1.1.4
set -e

cd "$(dirname "$0")"
if [ "$1" == "clean" ]; then
    ./genwin "$version" clean
    ./genlin "$version" clean
else
    ./genwin "$version"
    ./genlin "$version"
fi