#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Incorrect number of arguments given to $0, aborted"
    exit 1
fi

version="$1"
package=video2dreamcastdisc-$version-windows-x86
set -e

cd "$(dirname "$0")"
rm -rf $package $package.zip

# just clean built binaries/releases from source and exit now if given the 2nd argument 'clean'
if [ "$2" == "clean" ]; then
    rm -rf ffmpeg-git-full.7z ffmpeg-git-full
    exit 0
fi

mkdir -p $package/bin $package/licenses

# LegalADX
i686-w64-mingw32-gcc -static legaladx.c -o $package/bin/legaladx.exe

# FFmpeg/FFprobe
if [ ! -f "ffmpeg-git-full.7z" ]; then
    wget https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z
fi

if [ ! -d "ffmpeg-git-full" ]; then
    mkdir ffmpeg-git-full
    cd ffmpeg-git-full
    7z e ../ffmpeg-git-full.7z
    cd ../
fi

# copy binary files
cp -r \
ffmpeg-git-full/ffmpeg.exe \
ffmpeg-git-full/ffprobe.exe \
bin/cdrecord.exe \
bin/cygwin1.dll \
bin/sfd_player \
bin/IP.BIN \
bin/cdirip.exe \
bin/adxencd.exe \
bin/cdi4dc.exe \
bin/sfdmux.exe \
bin/Sfdmux.dll \
bin/mkisofs.exe \
bin/mkvmerge.exe \
$package/bin/

# copy and rename license files
cp unlicense.txt $package/licenses/video2dreamcastdisc.txt
cp pled/unlicense.txt $package/licenses/pled.txt
cp cdirip/LICENSE $package/licenses/cdirip-gpl2.txt
cp cdrtools/GPL-2.0.txt $package/licenses/cdrecord-gpl2.txt
cp cdrtools/CDDL.Schily.txt $package/licenses/cdrecord-cddl.txt
cp licenses/cdi4dc.txt $package/licenses/cdi4dc.txt
cp licenses/mkvmerge.txt $package/licenses/mkvmerge.txt
cp ffmpeg-git-full/LICENSE $package/licenses/ffmpeg.txt
cp ffmpeg-git-full/LICENSE $package/licenses/ffprobe.txt

# copy main files
cp -r \
readme.md \
images \
vid2dcd.bat \
config \
$package/

# convert text files EOL
dos2unix $package/config/video-bitrate.txt
dos2unix $package/config/burn-speed.txt

# send it
chmod -R 777 $package
zip -r $package.zip $package
