/*
BSD 3-Clause License

Copyright (c) 2022, Alex Free
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include <stdio.h>

char yn_response[2];
unsigned char buffer[19], byte;
int i, c;
FILE *illegal, *legal;
typedef enum { FALSE, TRUE } bool;
bool valid_input;

int main (int argc, const char * argv[]) {
	
	valid_input = FALSE;
	
	printf("LegalADX v1.0 By Alex Free (C)2022\n");
	
	if(argc != 3)
	{
		printf("\nUsage:\nlegaladx <audio.adx> <audio.sfa>\n\n<audio.adx> is an ADX file generated by converting a WAV to an ADX file with the adxencd tool.\n\n<audio.sfa> is the output file created by LegalADX, which is compatible with sfdmuxapp.exe and the Dreamcast Movie Creator from the Sega Dreamcast SDK.\n");
		return(1);
	}
	
	if((legal = fopen(argv[2], "r"))!= NULL)
	{
		printf("\nWarning: the desired output file %s already exists. Is it OK to overwrite it with a new file of the same name?\n", argv[2]);
		fclose(legal);

		while(!valid_input)
		{
			printf("(y/n): ");
			fgets(yn_response, 2, stdin);
			scanf("%*[^\n]");
			scanf("%*c");
		
			if(strcmp(yn_response,"y") == 0) 
			{
				valid_input = TRUE;
				if(remove(argv[2]) != 0)
				{
					printf("Error: failed to delete the file %s, aborting conversion\n", argv[2]);
					return(1);
				} 
				else 
				{
					printf("Successfully deleted the file %s for overwriting\n", argv[2]);
				} 
			} 
			else if(strcmp(yn_response,"n") == 0) 
			{
				valid_input = TRUE;
				printf("Aborted conversion\n");
				fclose(legal);
				return(1);
			} 
			else 
			{
				printf("Invalid input, please enter y or n\n");
			}
		}
	}
	
	legal = fopen(argv[2], "w+b");

	if((illegal = fopen(argv[1], "r+b"))!= NULL)
	{
		printf("\nConverting...\n");
		fseek(illegal, 0, 0);
		c = fgetc(illegal); // 0x80 first header byte
		buffer[0] = c;
		c = fgetc(illegal); // 0x00 second header byte
		buffer[1] = c;
// there are 2 copyright header offset bytes that sfdmux.dll/sfdmuxapp.exe/Dreamcast Movie Creator requires or else the file is deemed illegal by sfdmux.dll which prevents it from making an SFD file
		buffer[2] = 0x01;
		buffer[3] = 0x1C;
// this is the rest of the header, minus any sample looping functionality which is not supported and is disabled by some of the 0s later as it is not needed
		fseek(illegal, 4, SEEK_SET);
		for (i = 4; i < 19; i++) 
		{
			c = fgetc(illegal);
			buffer[i] = c;
		}
	} else {
	       printf("Error: Can not open the file %s for conversion\n", argv[1]);
	       return(1);
	}
	
	buffer[i] = '\0';
	fwrite(buffer, 1, 19, legal);
// this is the required padding for the copyright offset we set with the 2nd and 3rd bytes of this legal file
	for(i = 0; i < 252; i++)
	{
		fputc(0, legal);
	}

	c = 0;
// this writes the rest of the adx file's data into the legal file, making the legal file identical to the output of converting a .wav to a .sfa in Dreamcast Movie Creator
	while((c = fgetc(illegal)) != EOF)
	{
		byte = c;
		fputc(byte, legal);
	}

	fclose(illegal);
	fclose(legal);
	
	printf("\nDone! The output file %s is compatible with sfdmuxapp.exe/sfdmux.dll/Dreamcast Movie Creator.\n", argv[2]);

	return 0;
}